services:

#  etcd:
#    image: bitnami/etcd:latest
#    container_name: etcd
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
#    ports:
#      - "2379:2379"

  apisix:
    image: apache/apisix:latest
#    depends_on:
#      - etcd
    volumes:
      - ./apisix_logs:/usr/local/apisix/logs:Z
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:Z
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:Z
    ports:
      - "9080:9080"   # APISIX HTTP port
      - "9443:9443"   # APISIX HTTPS port
      # you can add /tcp 
      # - "9080:9080/tcp"
      # - "9443:9443/tcp"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: >
      start-dev
      --import-realm
      --spi-import-provider-dir=/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KEYCLOAK_FRONTEND_URL=http://localhost:8080
    volumes:
      - ./keycloak_conf/realm-export.json:/opt/keycloak/data/import/realm-export.json:Z
    ports:
      - "8080:8080"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8088:80"
