services:

  # nginx:
  #   image: nginx:latest
  #   # volumes:
  #   #   - ./nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
  #   #   - ./nginx/etc/nginx/certs/:/etc/nginx/certs/
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   # depends_on:
  #   #   - app

  app:
    build: .
    ports:
      - "9080:9080"
    environment:
      - KEYCLOAK_BASE_URL=http://keycloak:8080
    # depends_on:
    #   - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: >
      start-dev
      --import-realm
      --spi-import-provider-dir=/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KEYCLOAK_FRONTEND_URL=http://localhost:8080
    volumes:
      - ./keycloak_conf/realm-export.json:/opt/keycloak/data/import/realm-export.json:Z
    ports:
      - "8080:8080"
