version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - KEYCLOAK_BASE_URL=http://keycloak:8080
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
