apisix:
  node_listen: 9080
  enable_admin: true

deployment:
  admin:
    admin_key:
      - name: "admin"
        key: "admin"
        role: admin
  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30                     # 30 seconds
